### ISSUE TITLE
Feature: storing the request URL inside the table

### ISSUE THREAD

**Issue by jdehaan** [jbbarth/redmine_uhoh#2]
# Rationale

quite often it is helpful to reproduce the issue or test if it has gone. The backtrace information is not always pointing directly to the URL called by the user and has to be looked up inside the log files. This is obviously tedious and implementing a new column with that information would increase the usability a lot.

**Comment by nanego** [comment]
The URL information has just been added. Update to the latest version and you will see the new column.
